{{- if not .Values.sumologicservice.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sumologic-service.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "sumologic-service.labels" . | nindent 4 }}
type: Opaque
data:
  ACCESS_ID: {{ required "A valid ACCESS_ID is required to connect to the Sumo Logic API" .Values.sumologicservice.accessId | b64enc | quote }}
  ACCESS_KEY: {{ required "A valid ACCESS_KEY is required to connect to the Sumo Logic API" .Values.sumologicservice.accessKey | b64enc | quote }}

{{- end -}}